from collections import defaultdict
import asyncio


TOKENS_DATA = {
    'ASTER': {'price': 4, 'size': 2},
    'BTC': {'price': 1, 'size': 3},
    'ETH': {'price': 1, 'size': 3},
    'BNB': {'price': 1, 'size': 2},
    'SOL': {'price': 2, 'size': 2},
    'XRP': {'price': 4, 'size': 1},
    'DOGE': {'price': 5, 'size': 0},
    'HYPE': {'price': 3, 'size': 2},
    'ADA': {'price': 4, 'size': 0},
    'DOT': {'price': 3, 'size': 1},
    'SAND': {'price': 4, 'size': 0},
    '1000SHIB': {'price': 6, 'size': 0},
    'AXS': {'price': 3, 'size': 0},
    'MATIC': {'price': 4, 'size': 0},
    'LRC': {'price': 4, 'size': 0},
    'AVAX': {'price': 2, 'size': 0},
    'LTC': {'price': 2, 'size': 3},
    'GALA': {'price': 5, 'size': 0},
    'NEAR': {'price': 3, 'size': 0},
    'TRX': {'price': 5, 'size': 0},
    'FTM': {'price': 4, 'size': 0},
    'ATOM': {'price': 2, 'size': 2},
    'CAKE': {'price': 4, 'size': 0},
    'APE': {'price': 4, 'size': 0},
    'ETC': {'price': 2, 'size': 2},
    'GMT': {'price': 4, 'size': 0},
    'MANA': {'price': 4, 'size': 0},
    'IMX': {'price': 3, 'size': 0},
    'RUNE': {'price': 3, 'size': 0},
    'AAVE': {'price': 2, 'size': 1},
    'SKL': {'price': 5, 'size': 0},
    'ZIL': {'price': 5, 'size': 0},
    'DYDX': {'price': 3, 'size': 1},
    'SFP': {'price': 4, 'size': 0},
    'CRV': {'price': 3, 'size': 1},
    'COMP': {'price': 2, 'size': 3},
    'FIL': {'price': 3, 'size': 1},
    'PEOPLE': {'price': 5, 'size': 0},
    'KNC': {'price': 4, 'size': 0},
    'OGN': {'price': 4, 'size': 0},
    'VET': {'price': 5, 'size': 0},
    'LINK': {'price': 3, 'size': 0},
    'IOST': {'price': 6, 'size': 0},
    'MTL': {'price': 4, 'size': 0},
    'BCH': {'price': 1, 'size': 3},
    'SNX': {'price': 3, 'size': 1},
    'EOS': {'price': 3, 'size': 1},
    'UNI': {'price': 3, 'size': 0},
    'JASMY': {'price': 6, 'size': 0},
    'LINA': {'price': 5, 'size': 0},
    'ZRX': {'price': 4, 'size': 1},
    'KAVA': {'price': 4, 'size': 1},
    'ALICE': {'price': 3, 'size': 1},
    'CHZ': {'price': 5, 'size': 0},
    'ALGO': {'price': 4, 'size': 0},
    'ENS': {'price': 3, 'size': 1},
    'GAL': {'price': 4, 'size': 0},
    'LUNA2': {'price': 4, 'size': 0},
    'OP': {'price': 4, 'size': 1},
    'WOO': {'price': 5, 'size': 0},
    'BEL': {'price': 4, 'size': 0},
    'APT': {'price': 3, 'size': 1},
    'MASK': {'price': 3, 'size': 0},
    'BAND': {'price': 4, 'size': 1},
    'ID': {'price': 4, 'size': 0},
    'ARB': {'price': 4, 'size': 1},
    'INJ': {'price': 3, 'size': 1},
    'SUI': {'price': 4, 'size': 0},
    'CFX': {'price': 4, 'size': 1},
    '1000PEPE': {'price': 6, 'size': 0},
    'SXP': {'price': 4, 'size': 0},
    'LDO': {'price': 4, 'size': 0},
    'ARPA': {'price': 5, 'size': 0},
    'EDU': {'price': 4, 'size': 0},
    'MKR': {'price': 1, 'size': 3},
    'TRB': {'price': 2, 'size': 1},
    'BIGTIME': {'price': 4, 'size': 0},
    'PERP': {'price': 4, 'size': 0},
    'WLD': {'price': 4, 'size': 0},
    'CYBER': {'price': 3, 'size': 0},
    'XLM': {'price': 4, 'size': 0},
    'YGG': {'price': 4, 'size': 0},
    'FET': {'price': 4, 'size': 0},
    'PENDLE': {'price': 4, 'size': 0},
    'SEI': {'price': 4, 'size': 0},
    'C98': {'price': 4, 'size': 0},
    '1INCH': {'price': 4, 'size': 0},
    'LOOM': {'price': 4, 'size': 0},
    'STX': {'price': 4, 'size': 0},
    'RIF': {'price': 5, 'size': 0},
    'MINA': {'price': 4, 'size': 0},
    '1000FLOKI': {'price': 5, 'size': 0},
    'BLZ': {'price': 4, 'size': 0},
    'GAS': {'price': 3, 'size': 1},
    'ORDI': {'price': 3, 'size': 1},
    'MBL': {'price': 6, 'size': 0},
    'MANTA': {'price': 4, 'size': 1},
    'TIA': {'price': 4, 'size': 0},
    'ONDO': {'price': 4, 'size': 1},
    'PYTH': {'price': 5, 'size': 0},
    'PIXEL': {'price': 4, 'size': 0},
    'GRT': {'price': 5, 'size': 0},
    'AI': {'price': 5, 'size': 0},
    'ARKM': {'price': 4, 'size': 0},
    'NFP': {'price': 4, 'size': 1},
    'RLC': {'price': 4, 'size': 1},
    'NMR': {'price': 2, 'size': 1},
    'STRK': {'price': 4, 'size': 1},
    'TON': {'price': 4, 'size': 1},
    '1000BONK': {'price': 6, 'size': 0},
    'BLAST': {'price': 5, 'size': 0},
    'LISTA': {'price': 4, 'size': 1},
    'MERL': {'price': 3, 'size': 1},
    'IO': {'price': 2, 'size': 1},
    'ZK': {'price': 4, 'size': 1},
    'EIGEN': {'price': 2, 'size': 1},
    'TRUMP': {'price': 3, 'size': 2},
    'FARTCOIN': {'price': 4, 'size': 1},
    'ENA': {'price': 4, 'size': 0},
    'MOODENG': {'price': 5, 'size': 0},
    'WIF': {'price': 0, 'size': 1},
    'NEIRO': {'price': 7, 'size': 0},
    'B': {'price': 4, 'size': 0},
    'USD1': {'price': 4, 'size': 0},
    'JANITOR': {'price': 5, 'size': 0},
    'SAHARA': {'price': 5, 'size': 1},
    'AFEE': {'price': 4, 'size': 1},
    'PUMP': {'price': 6, 'size': 0},
    'AAPL': {'price': 2, 'size': 2},
    'TSLA': {'price': 2, 'size': 2},
    'NVDA': {'price': 2, 'size': 2},
    'AMZN': {'price': 2, 'size': 2},
    'META': {'price': 2, 'size': 2},
    'GOOG': {'price': 2, 'size': 2},
    'MSFT': {'price': 2, 'size': 2},
    'PENGU': {'price': 6, 'size': 0},
    'SBET': {'price': 2, 'size': 2},
    'SPK': {'price': 5, 'size': 0},
    'PORT3': {'price': 5, 'size': 0},
    'TREE': {'price': 4, 'size': 0},
    'ZRC': {'price': 5, 'size': 0},
    'ESPORTS': {'price': 5, 'size': 0},
    'ZORA': {'price': 5, 'size': 0},
    'TAG': {'price': 7, 'size': 0},
    'C': {'price': 5, 'size': 0},
    'IN': {'price': 5, 'size': 0},
    'TOWNS': {'price': 5, 'size': 0},
    'PROVE': {'price': 4, 'size': 0},
    'XNY': {'price': 6, 'size': 0},
    'AIO': {'price': 5, 'size': 0},
    'DAM': {'price': 5, 'size': 0},
    'SAPIEN': {'price': 5, 'size': 0},
    'CUDIS': {'price': 5, 'size': 0},
    'WLFI': {'price': 4, 'size': 0},
    'XPL': {'price': 4, 'size': 0},
    'BAS': {'price': 6, 'size': 0},
    'BTR': {'price': 5, 'size': 0},
    'MITO': {'price': 5, 'size': 0},
    'HEMI': {'price': 6, 'size': 0},
    'LINEA': {'price': 5, 'size': 0},
    'Q': {'price': 6, 'size': 0},
    'PTB': {'price': 5, 'size': 0},
    'ARIA': {'price': 5, 'size': 0},
    'TAKE': {'price': 5, 'size': 0},
    'AVNT': {'price': 4, 'size': 0},
    'OPEN': {'price': 4, 'size': 0},
    'FLOCK': {'price': 4, 'size': 0},
    'SKY': {'price': 5, 'size': 0},
    'QQQ': {'price': 2, 'size': 2},
    'HOLO': {'price': 4, 'size': 0},
    'UB': {'price': 6, 'size': 0},
    'XPIN': {'price': 7, 'size': 0},
    'ZKC': {'price': 4, 'size': 0},
}

address_locks = defaultdict(asyncio.Lock)

class MultiLock:
    def __init__(self, addresses: list[str]):
        self.locks = [address_locks[addr] for addr in sorted(addresses)]
        self.acquired: list[asyncio.Lock] = []

    async def __aenter__(self):
        while True:
            if all(not lock.locked() for lock in self.locks):
                for lock in self.locks:
                    await lock.acquire()
                    self.acquired.append(lock)
                return self
            await asyncio.sleep(1)

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        for lock in reversed(self.acquired):
            lock.release()
        self.acquired.clear()
